/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import Dao.InsertDataDao;
import model.Data;

/**
 *
 * @author admin
 */
public class UpdateData extends javax.swing.JFrame {

    /**
     * Creates new form UpdateData
     */
    public UpdateData() 
    {
        initComponents();
        btnUpdate.setEnabled(false);
        disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        txtbt = new javax.swing.JTextField();
        txtsname = new javax.swing.JTextField();
        txtenroll = new javax.swing.JTextField();
        txtbranch = new javax.swing.JTextField();
        lenroll = new javax.swing.JLabel();
        lbt = new javax.swing.JLabel();
        lsname = new javax.swing.JLabel();
        lbranch = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Data");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        l1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 255));
        l1.setText("Update Student Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 111, 0, 0);
        jPanel1.add(l1, gridBagConstraints);

        txtbt.setFont(new java.awt.Font("Arial for oup 97", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 34, 0, 0);
        jPanel1.add(txtbt, gridBagConstraints);

        txtsname.setFont(new java.awt.Font("Arial for oup 97", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 34, 0, 0);
        jPanel1.add(txtsname, gridBagConstraints);

        txtenroll.setFont(new java.awt.Font("Arial for oup 97", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 34, 0, 0);
        jPanel1.add(txtenroll, gridBagConstraints);

        txtbranch.setFont(new java.awt.Font("Arial for oup 97", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 34, 0, 0);
        jPanel1.add(txtbranch, gridBagConstraints);

        lenroll.setFont(new java.awt.Font("Arial for oup 97", 1, 18)); // NOI18N
        lenroll.setText("Enrollment no.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 28, 0, 0);
        jPanel1.add(lenroll, gridBagConstraints);

        lbt.setFont(new java.awt.Font("Arial for oup 97", 1, 18)); // NOI18N
        lbt.setText("BT no.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 28, 0, 0);
        jPanel1.add(lbt, gridBagConstraints);

        lsname.setFont(new java.awt.Font("Arial for oup 97", 1, 18)); // NOI18N
        lsname.setText("Student Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 28, 0, 0);
        jPanel1.add(lsname, gridBagConstraints);

        lbranch.setFont(new java.awt.Font("Arial for oup 97", 1, 18)); // NOI18N
        lbranch.setText("Branch");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 28, 0, 0);
        jPanel1.add(lbranch, gridBagConstraints);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setMnemonic('u');
        btnUpdate.setText("Update Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 34, 0, 0);
        jPanel1.add(btnUpdate, gridBagConstraints);

        jLabel5.setText("©Amit Kushwah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 152, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setMnemonic('s');
        btnSearch.setText("Search Record");
        btnSearch.setToolTipText("Search record to be update");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 135, 0, 0);
        jPanel1.add(btnSearch, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         try
        {
        int n;
        n=JOptionPane.showConfirmDialog(this, "Are you sure want to update", "Save record",JOptionPane.YES_NO_OPTION);
        if(n==0)
        {
            
            String bt,sname,enroll,branch;
            bt=txtbt.getText();
            sname=txtsname.getText();
            enroll=txtenroll.getText();
            branch=txtbranch.getText();
            Data D=new Data();
            D.setBt(bt);
            D.setSnmae(sname);
            D.setEn(enroll);
            D.setBranch(branch);
            InsertDataDao id=new InsertDataDao();
            if(id.update_student(D))
            {
                JOptionPane.showMessageDialog(this, "Record updated...");
            }
           txtbt.setText("");
           txtsname.setText("");
           txtenroll.setText("");
           txtbranch.setText("");
           disable();
           btnUpdate.setEnabled(false);
        }
         
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
     
        String BTno=null;
        BTno=JOptionPane.showInputDialog(this, "Enter BTno for search");
       if(BTno==null)
                 System.out.println("");
      else
       {
         try{  
         InsertDataDao id=new InsertDataDao();
          Data  D=null;
          D=id.searchByBtno(BTno);
           if(D==null)
            JOptionPane.showMessageDialog(this, "Record not found.......");
        else
        {
           txtbt.setText(D.getBt());
           txtsname.setText(D.getSnmae());
           txtenroll.setText(D.getEn());
           txtbranch.setText(D.getBranch());
           enable();
           btnUpdate.setEnabled(true);
        }
        }catch(Exception e){
            System.out.println(e);
       } 
      } 
        
         
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel lbranch;
    private javax.swing.JLabel lbt;
    private javax.swing.JLabel lenroll;
    private javax.swing.JLabel lsname;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JTextField txtbt;
    private javax.swing.JTextField txtenroll;
    private javax.swing.JTextField txtsname;
    // End of variables declaration//GEN-END:variables
public void disable()
{
    txtbt.setEnabled(false);
    txtsname.setEnabled(false);
    txtenroll.setEnabled(false);
    txtbranch.setEnabled(false);
}
public void enable()
{
    txtsname.setEnabled(true);
    txtenroll.setEnabled(true);
    txtbranch.setEnabled(true);
}
}
